### ISSUE TITLE
Random output on Android?

### ISSUE THREAD

**Issue by AmarOk1412** [NSTiwari/Gemma-on-Android#6]
Hi,

I used your colab book to do a bot:

https://huggingface.co/AmarOk1412/fine_tuned_science_gemma2b-it/tree/main

Modified playbook is there: https://gist.github.com/AmarOk1412/edf86f72966768177b685099b76499a7#file-fine_tune_gemma_model-ipynb

Basically, the change is that I train with:

```
prompt = """

Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.
You're a bot parsing ingredients from recipes that needs to provide a structure to use in a list. The answer is a list of ingredients with optional quantrity and unit.
There can be several ingredients in the same input. This will result in a list with multiple ingredients. e.g. 'sel et poivre' will give 	"sel" and "poivre" as ingredients.
Remove useless words, e.g. "sel au goût", "au goût" is not a part of the ingredient and useless in the list.

### Instruction:
{}

### Input:
{}

### Response:
{}"""
```

It works well for "Step 6: Inference on the fine-tuned model."

```
### Instruction:
parse

### Input:
sel et poivre

### Response:
[{'ingredient': 'sel', 'quantity': 'None', 'unit': 'None'}, {'ingredient': 'poivre', 'quantity': 'None', 'unit': 'None'}]
```

However, once I used the converted scigemma.bin. I can't make it work. Every result seems random

Is it a known issue?

**Comment by AmarOk1412** [comment]
Note. If I use the code https://huggingface.co/spaces/Aashi/NSTiwari-fine_tuned_science_gemma2b-it/blob/main/app.py, the model seems to work (except in requirements.txt gradio is missing)

**Comment by NSTiwari** [comment]
The problem could be when the model is converted into TF Lite (.bin) format after quantization. What was the size of your training dataset?

**Comment by AmarOk1412** [comment]
1121 rows (available there: https://huggingface.co/datasets/AmarOk1412/ingredients) so pretty small

**Comment by NSTiwari** [comment]
Yeah, that's too small of a dataset. Try to increase the size, that should make some difference.

**Comment by AmarOk1412** [comment]
How much data would be enough?

In the article, the dataset seems smaller: https://huggingface.co/datasets/Aashi/Science_Q_and_A_dataset (1020 rows)

**Comment by AmarOk1412** [comment]
Ok I increased the size of the dataset to be around 5k entries and still the same result.
